services:
  traefik:
    image: traefik:v3.0
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--api.dashboard=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=kreker2112@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/dynamic.yml:/etc/traefik/dynamic.yml"
    networks:
      - app-network

  backend:
    build:
      context: ./backend/EnterpreneurCabinetAPI
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ./backend/EnterpreneurCabinetAPI/appsettings.json:/app/appsettings.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.tax-cabinet.pp.ua`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.middlewares=redirect-to-https@file"
      - "traefik.http.routers.backend-secure.rule=Host(`api.tax-cabinet.pp.ua`)"
      - "traefik.http.routers.backend-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-secure.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`tax-cabinet.pp.ua`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.middlewares=redirect-to-https@file"
      - "traefik.http.routers.frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend-secure.rule=Host(`tax-cabinet.pp.ua`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
